config/routes.rb
HorowitzRealEstate::Application.routes.draw do
  get "history_record/index"
  get "city/index"
  get "neighborhoods/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :listings do
    member do
      get :copy
      post :toggle_favorite
    end
    collection do
      post :create_email
      post :send_email
    end
  end
  resources :neighborhoods
  resources :history_records, only: [:index]

  resources :reports, only: [] do
    collection do
      get :listings_by_period
      get :rented_listings_by_period
    end
  end

  root  'listings#index'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
	has_many :listings
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  require 'prawnto'
  before_filter :index_page_filter, only: [:index]
  before_filter :signed_in_user, except: [:index]
  before_filter :correct_user, only: [:edit, :update, :destroy, :copy]

  # helper_method :sort_column, :sort_direction

  def index
    if sort_column.include? '.'
      parts = sort_column.split('.')
      @listings = Listing.includes(parts.first).order("#{parts.first.pluralize}.#{parts.last}" + ' ' + sort_direction)
    else
      @listings = Listing.includes(:property_photos, :neighborhood, :bed, :status).order(sort_column + ' ' + sort_direction)
    end

    if params[:status].present?
      if params[:status] == 'Active'
        @listings = @listings.available_listings
      elsif params[:status] == 'Unavailable'
        @listings = @listings.hidden_listings
      elsif params[:status] == 'Pending'
        @listings = @listings.pending_listings
      end
    else
      @listings = @listings.available_listings
    end

    favorite_ids = []
    favorite_ids = Favorite.where(user_id: current_user.try(:id)).pluck :listing_id

    @listings = @listings.ids_filter(params[:ids]) if (params[:ids].present? && params[:ids] != [''])
    @listings = @listings.ids_filter(favorite_ids) if (params[:favorites].present?)
    @listings = @listings.street_address_search(params[:street_address]) if params[:street_address].present?
    @listings = @listings.listing_type_filter(params[:listing_type_id]) if params[:listing_type_id].present?
    @listings = @listings.type_filter(params[:property_type]) if params[:property_type].present?
    @listings = @listings.beds(params[:beds]) if params[:beds].present?
    @listings = @listings.neighborhood_filter(params[:neighborhood_ids]) if params[:neighborhood_ids].present?
    @listings = @listings.min_price(params[:price_from]) if params[:price_from].present?
    @listings = @listings.max_price(params[:price_to]) if params[:price_to].present?

    @listings = @listings.full_baths(params[:full_baths]) if params[:full_baths].present?

    @listings = @listings.half_baths(params[:half_baths]) if params[:half_baths].present?
    @listings = @listings.agent_filter(params[:agent_id]) unless params[:agent_id].blank?

    @listings = @listings.dishwasher_filter(params[:dishwasher]) if params[:dishwasher].present?
    @listings = @listings.backyard_filter(params[:backyard]) if params[:backyard].present?
    @listings = @listings.balcony_filter(params[:balcony]) if params[:balcony].present?
    @listings = @listings.elevator_filter(params[:elevator]) if params[:elevator].present?
    @listings = @listings.walk_up_filter(params[:walk_up]) if params[:walk_up].present?
    @listings = @listings.laundry_in_building_filter(params[:laundry_in_building]) if params[:laundry_in_building].present?
    @listings = @listings.laundry_in_unit_filter(params[:laundry_in_unit]) if params[:laundry_in_unit].present?
    @listings = @listings.live_in_super_filter(params[:live_in_super]) if params[:live_in_super].present?
    @listings = @listings.absentee_landlord_filter(params[:absentee_landlord]) if params[:absentee_landlord].present?
    @listings = @listings.parking_available_filter(params[:parking_available]) if params[:parking_available].present?
    @listings = @listings.storage_available_filter(params[:storage_available]) if params[:storage_available].present?
    @listings = @listings.yard_filter(params[:yard]) if params[:yard].present?
    @listings = @listings.patio_filter(params[:patio]) if params[:patio].present?

    @listings = @listings.no_pets_filter(params[:no_pets]) if params[:no_pets].present?
    @listings = @listings.cats_filter(params[:cats]) if params[:cats].present?
    @listings = @listings.dogs_filter(params[:dogs]) if params[:dogs].present?
    @listings = @listings.approved_pets_only_filter(params[:approved_pets_only]) if params[:approved_pets_only].present?

    @listings = @listings.heat_filter(params[:heat]) if params[:heat].present?
    @listings = @listings.gas_filter(params[:gas]) if params[:gas].present?
    @listings = @listings.all_filter(params[:all_utilities]) if params[:all_utilities].present?
    @listings = @listings.none_filter(params[:none]) if params[:none].present?

    @neighborhoods_json = ''
    if params['neighborhood_ids'].present?
      @neighborhoods_json = Neighborhood.where(id: params['neighborhood_ids'].split(',')).map(&:attributes).to_json
    end

    @sale_id = ListingType.find_by(name: 'Sale').id
    @rental_id = ListingType.find_by(name: 'Rental').id
    @commercial_id = ListingType.find_by(name: 'Commercial').id

    respond_to do |format|
      format.html {
        @listings = @listings.paginate(page: params[:page])
        @favorites_ids = current_user.favorites.pluck :listing_id
      }
      format.pdf {
        render pdf: 'index'
      }
      format.xml do
        if params[:to].to_s.downcase == 'nakedapartments'
          @listings = Listing.where(export_to_nakedapartments: true)
        elsif params[:to].to_s.downcase == 'streeteasy'
          @listings = Listing.where(export_to_streeteasy: true)
        elsif params[:to].to_s.downcase == 'zumper'
          @listings = Listing.where(export_to_zumper: true,
                                    status_id: Status.where.not(name: %w(Closed Lost Rented Withdrawn)).pluck(:id))
        elsif params[:to].to_s.downcase == 'myastoria'
          @listings = Listing.where export_to_myastoria: true
        else
          @listings = []
        end

        unless @listings.empty?
          if params[:type].to_s.downcase == 'rental'
            @listings = @listings.listing_type_filter(ListingType.find_by_name('Rental').id)
          elsif params[:type].to_s.downcase == 'sale'
            @listings = @listings.listing_type_filter(ListingType.find_by_name('Sale').id)
          elsif params[:type].to_s.downcase == 'all'
            @listings = @listings
          else
            @listings = []
          end
        end
        unless @listings.empty?
          if params[:to].to_s.downcase == 'nakedapartments'
            @listings.update_all(exported_to_nakedapartments: true)
          elsif params[:to].to_s.downcase == 'streeteasy'
            @listings.update_all(exported_to_streeteasy: true)
          elsif params[:to].to_s.downcase == 'zumper'
            @listings.update_all(exported_to_zumper: true)
          elsif params[:to].to_s.downcase == 'myastoria'
            @listings.update_all(exported_to_myastoria: true)
          end
        end
      end
    end

    #if params[:display].present?
    #	@display = params[:display]
    #else
    #	@display = 'thumb_list'
    #end
  end


  # class ApplicationController < ActionController::Base
  #   rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  #
  #   def render_404
  #     respond_to do |format|
  #       format.html { render :action => "errors/404.html.erb", :status => 404 }
  #       # and so on..
  #     end
  #   end
  # end
  # Yes, you can also do a redirect instead of render, but this is not a good idea. Any semi-automatic interaction
  # with your site will think that the transfer was successfull (because the returned code was not 404),
  # but the received resource was not the one your client wanted.
  def show
    begin
      @listing = Listing.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, :flash => {:error => 'Record not found.'}
      return
    end

    #@photo_urls = @listing.property_photos.all
    respond_to do |format|
      format.html
      format.pdf {
        prawnto :inline => true, :prawn => {:margin => 20}
        render :pdf => 'show'
      }
      format.xml
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])

    # if params[:main_photo].present?
    #   preloaded = Cloudinary::PreloadedFile.new(params[:main_photo])
    #   raise "Invalid upload signature" if !preloaded.valid?
    #   @listing.main_photo = preloaded.identifier
    # end
    old_status_id = @listing.status_id
    if @listing.update_attributes(listing_params)
      flash[:success] = "Listing updated"
      PropertyVideo.where(listing_id: @listing.id).destroy_all
      PropertyVideo.create(listing_id: @listing.id,video_url: params[:video_url] )
      if old_status_id != @listing.status_id
        history = @listing.history_records.build
        history.message = "Status changed from '#{Status.find(old_status_id).try(:name)}' to '#{@listing.status.name}' by #{current_user.name}"
        history.save
        AgentMailer.listing_changed(@listing, Status.find(old_status_id).try(:name), @listing.status.name, current_user).deliver
      end

      # xml_content = render_to_string :action => 'show', :formats => [:xml]
      # url = URI.parse('http://myastoriarealestate.com/xml/')
      # url = URI.parse('http://127.0.0.1:3000/xml/')
      # request = Net::HTTP::Post.new(url.path)
      # request.body = xml_content
      # request.content_type = 'text/xml'
      # request.content_length =xml_content.bytesize()
      # response = Net::HTTP.request #start(url.host, url.port) {|http| http.request(request)}

      # HTTParty.post('http://127.0.0.1:3000/xml/', :body => xml_content )
      redirect_to @listing
    else
      render 'edit'
    end
  end

  def new
    @listing = current_user.listings.build
    puts @listing.inspect
    if params[:listing_type_id].present?
      @listing.listing_type_id = params[:listing_type_id]
    end
  end

  def create
    if params[:Neighborhood].present?
      neighborhood = Neighborhood.find_by_name(params[:Neighborhood])
      if neighborhood.nil?
        neighborhood = Neighborhood.create(name: params[:Neighborhood])
      end
      if neighborhood.id != params[:listing][:neighborhood_id]
        params[:listing][:neighborhood_id] = neighborhood.id
      end
    end

app/helpers/listings_helper.rb
module ListingsHelper
	def link_to_add_fields(name, f, association)
		link_to name, '#', class: 'add_fields', data: object_fields( f, association)
  end

  def object_fields(f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    { id: id, fields: fields.gsub("\n", '') }
  end

	def link_to_remove_fields(name, f)
    	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def filter_check_box_tag(name, value = nil)
    check_box_tag name, (value unless value.blank?), (value != '0' unless value.blank?)
  end



  def sortable_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    ds = display_helper
    glyph =''
    if column == sort_column
      if direction == 'asc'
        glyph = tag 'i', class: "glyphicon glyphicon-arrow-up"
      else
        glyph = tag 'i', class: "glyphicon glyphicon-arrow-down"
      end
    end
    params_for_link = params.clone || {}
    params_for_link[:sort] = column
    params_for_link[:direction] = direction
    params_for_link[:display] = ds

    link_to( title, params_for_link ) +' ' + glyph
  end

  def status_for_export(status)
    #active|off-market|temp-off-market|in-contract|contract-out|contract-signed|sold|rented
    if status == 'New'
      return 'active'
    end
    if status == 'Accepted offer'
      return 'active'
    end
    if status == 'Under contract'
      return 'in-contract'
    end
    if status == 'Price change'
      return 'active'
    end
    if status == 'Closed'
      return 'off-market'
    end
    if status == 'Temporary off market'
      return 'temp-off-market'
    end
    if status == 'Withdrawn'
      return 'active'
    end
    if status == 'Deposit/Pending Application'
      return 'active'
    end
    if status == 'Lost'
      return 'rented'
    end
    if status == 'Rented'
      return 'rented'
    end

    status
  end

  def bed_for_export(bed)
    if bed == 'Studio'
      return 0
    end
    if (bed == 'Junior 1') or (bed == '1 Bedroom') or (bed == '1 Bedroom plus den')
      return 1
    end

    if (bed == 'Junior 4') or (bed == '4 Bedroom')
      return 4
    end

    if (bed == '2 Bedroom') or (bed == '2 Bedroom plus den')
      return 2
    end

    if bed == '3 Bedroom'
      return 3
    end

    0
  end

  def property_type_for_export(property_type)
  #   condo|coop|townhouse|condop|rental|house|other
    if property_type == 'Private House'
      return 'house'
    end
    if property_type == 'Multi-family'
      return 'other'
    end
    if property_type == 'Coop'
      return 'coop'
    end
    if property_type == 'Condo'
      return 'condo'
    end
    'other'
  end

  def zumper_property_type_for_export(property_type)
    if property_type == 'Private House'
      return 'townhouse'
    end
    if property_type == 'Multi-family'
      return 'multi-family'
    end
    if property_type == 'Coop'
      return 'coop'
    end
    if property_type == 'Condo'
      return 'condo'
    end
    'apartment/condo/townhouse'
  end

  def zumper_status_for_export(status)
    # for rent | for sale | pending
    # | active contingent | sold |
    #              withdrawn | rented | off market
    if status == 'New'
      return 'for rent'
    end
    if status == 'Accepted offer'
      return 'for rent'
    end
    if status == 'Under contract'
      return 'rented'
    end
    if status == 'Price change'
      return 'for rent'
    end
    if status == 'Closed'
      return 'off market'
    end
    if status == 'Temporary off market'
      return 'off market'
    end
    if status == 'Withdrawn'
      return 'withdrawn'
    end
    if status == 'Deposit/Pending Application'
      return 'pending'
    end
    if status == 'Lost'
      return 'off market'
    end
    if status == 'Rented'
      return 'rented'
    end

    status
  end
end

app/views/listings/_email_listing_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Заголовок модального окна -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="myModalLabel">Input email address</h4>
      </div>
      <!-- Основная часть модального окна, содержащая форму для регистрации -->
      <div class="modal-body">
        <!-- Форма для регистрации -->
        <%= form_tag send_email_listings_path, id:'send_email_form', role: 'form', class: 'form-horizontal' do -%>

            <!-- Блок для ввода email -->
          <div class="form-group has-feedback">
            <%= label_tag 'email', nil,  class: 'control-label col-xs-3'  %>
            <div class="col-xs-6">
              <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                <%= email_field_tag 'email', nil, id: 'email', class: 'form-control', required: 'required' %>
              </div>
              <span class="glyphicon form-control-feedback"></span>
            </div>
          </div>
          <!-- Конец блока для ввода email-->
        <% end %>
      </div>
      <!-- Нижняя часть модального окна -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="send" type="button" class="btn btn-primary">Send</button>
      </div>
    </div>
  </div>
</div>

app/views/listings/_listing_type_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create</h4>
      </div>
      <div class="modal-body">
        Create  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/listings/create_email.html.erb
<% provide(:title, 'Create email') %>
<div class="row">
  <div class="col-md-12">
    <%= form_for :listing, url: send_email_listings_path do |f| %>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Listings</div>
            <ul class="list-group">
              <% @listings.each do |listing| %>
                <li class="list-group-item">
                  <%= hidden_field_tag 'listing_ids[]', listing.id %>
                  <%= listing.full_address %>
                </li>
              <% end %>
            </ul>
          </div>
        <div class="form-group">
          <%= label_tag 'Email' %>
          <%= text_field_tag 'email', nil, class: 'form-control' %>
        </div>
        <%= f.submit 'Send', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<% provide :title, 'Listings' %>
<div class="row row-offcanvas row-offcanvas-left">

  <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
    <%= form_tag(listings_path, :method => :get, role: 'form', id: 'filter_form') do %>
        <%= render 'filter_fields' %>
    <% end %>
  </div><!--/.sidebar-offcanvas-->

  <div class="col-xs-12 col-sm-9">
    <p class="pull-left visible-xs">
      <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle sidebar</button>
    </p>
    <div class="page-header">
      <h1>Listings
        <small>Use sidebar to filter listings.</small>
      </h1>
    </div>
    <div class="row">
      <%= render 'listings_content' %>
    </div><!--/row-->
  </div><!--/.col-xs-12.col-sm-9-->

</div>

app/views/listings/show.html.erb
<% provide(:title, @listing.full_address) %>

<% unless @listing.listing_type.try(:name) == 'Commercial' %>
<div class="row" xmlns="http://www.w3.org/1999/html">
  <div class="col-md-8">
    <h1 id="address" data-value="<%= @listing.full_address %>">
      <%= @listing.internal_headline %>
      <small><span class="label label-info"><%= @listing.listing_type.name unless @listing.listing_type.nil? %></span>
      </small>
      <% if @listing.export_to_nakedapartments? %>
          <%
             if @listing.exported_to_nakedapartments?
               class_name = 'success'
             else
               class_name = 'default'
             end
          %>
          <small>
            <span class="label label-<%= class_name %>">NA</span>
          </small>
      <% end %>
      <% if @listing.export_to_streeteasy? %>
          <%
             if @listing.exported_to_streeteasy?
               class_name = 'success'
             else
               class_name = 'default'
             end
          %>
          <small>
            <span class="label label-<%= class_name %>">SE</span>
          </small>
      <% end %>
      <% if @listing.export_to_myastoria? %>
      <%
         if @listing.exported_to_myastoria?
           class_name = 'success'
         else
           class_name = 'default'
         end
      %>
          <small>
            <span class="label label-<%= class_name %>">MA</span>
          </small>
      <% end %>
      <% if @listing.export_to_zumper? %>
          <%
             if @listing.exported_to_zumper?
               class_name = 'success'
             else
               class_name = 'default'
             end
          %>
          <small>
            <span class="label label-<%= class_name %>">ZU</span>
          </small>
      <% end %>
    </h1>
    <h3 class="zip">
      <%= "Address: #{@listing.full_address}" if @listing.title.present? %>
      <%= "Unit no: #{@listing.unit_no}" unless @listing.unit_no.nil? || @listing.unit_no.empty? %>
      <%= "Zip: #{@listing.zip_code}" unless @listing.zip_code.nil? %>
    </h3>
  </div>

  <div class="col-md-4">
    <h2 class="text-right"><%= number_to_currency(@listing.price) %></h2>

    <h3 class="property_type text-right"><%= @listing.property_type.name unless @listing.property_type.nil? %></h3>
  </div>
</div>
<p>
  <% if signed_in? %>
      <% if current_user?(@listing.user) || current_user.admin? %>
          <%= link_to 'Edit listing', edit_listing_path(@listing), class: 'btn btn-default', role: 'button' %>
          <!-- TODO: make post request via form -->
          <%= link_to 'Copy listing', copy_listing_path(@listing), class: 'btn btn-default', role: 'button' %>
          <%= link_to 'Delete listing', @listing, method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-default', role: 'button' %>
          <%= link_to 'History', history_records_path(listing_id: @listing.id), class: 'btn btn-default', role: 'button' %>
      <% end %>
  <% end %>
  <%= link_to 'Download Flyer', listing_path(@listing, :format => 'pdf'), class: 'btn btn-primary', role: 'button' %>
</p>

<div class="row">
  <% if @listing.user.present? %>
  <div class="col-md-12">
    <h3><span class="property_type">Agent:</span> <%= @listing.user.try :name %>
      <%= link_to 'View agent', @listing.user, class: 'btn btn-xs btn-primary', role: 'button' %>
      <%= mail_to @listing.user.email, 'Contact agent', class: 'btn btn-xs btn-primary', role: 'button' %>
    </h3>
  </div>
  <% end %>

  <% unless @listing.landlord.nil? %>
      <div class="col-md-12">
        <h3>
          <span class="property_type">Landlord:</span> <%= @listing.landlord %>
        </h3>
      </div>
  <% end %>

  <% if @listing.access.present? %>
      <div class="col-md-12">
        <h3>
          <span class="property_type">Access:</span> <%= @listing.access %>
        </h3>
      </div>
  <% end %>
</div>


<div class="row">
  <div class="col-md-7 connected-carousels">
    <% if @listing.property_photos.count+@listing.property_floorplans.count+@listing.property_videos.count > 0 %>
       
            <%= render 'jcarousel' %>
        
    <% else %>
        <%= image_tag('no_photo.png', :width => '100%') %>
    <% end %>
  </div>

  <div class="col-md-5 property-rooms">
    <p><%= @listing.bed.name %></p>

    <p><%= @listing.full_baths_no %> full baths</p>

    <p><%= @listing.half_baths_no %> half baths</p>

    <p>Days on market: <%= @listing.days_on_market %></p>

    <p>Available at: <%= @listing.available_date %></p>

    <p><%= @listing.status.try :name %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-7 property-description">
    <%= simple_format(@listing.description).html_safe %>
  </div>
  <div class="col-md-5 property-size text-right">
    <div id="map-canvas"></div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% unless @listing.features.empty? %>
        <p><strong>Features:</strong> <%= @listing.features %></p>
    <% end %>
    <% unless @listing.pets.empty? %>
        <p><strong>Pets:</strong> <%= @listing.pets %></p>
    <% end %>
    <% unless @listing.utilities.empty? %>
        <p><strong>Utilities included:</strong> <%= @listing.utilities %></p>
    <% end %>
  </div>
</div>

<% else %>

    <div class="row" xmlns="http://www.w3.org/1999/html">
      <div class="col-md-8">
        <h1 id="address" data-value="<%= @listing.full_address %>">
          <%= @listing.full_address %>
          <small><span class="label label-info"><%= @listing.listing_type.name unless @listing.listing_type.nil? %></span>
          </small>
          <% if @listing.export_to_nakedapartments? %>
              <%
                 if @listing.exported_to_nakedapartments?
                   class_name = 'success'
                 else
                   class_name = 'default'
                 end
              %>
              <small>
                <span class="label label-<%= class_name %>">NA</span>
              </small>
          <% end %>
          <% if @listing.export_to_streeteasy? %>
              <%
                 if @listing.exported_to_streeteasy?
                   class_name = 'success'
                 else
                   class_name = 'default'
                 end
              %>
              <small>
                <span class="label label-<%= class_name %>">SE</span>
              </small>
          <% end %>
          <% if @listing.export_to_myastoria? %>
              <%
                 if @listing.exported_to_myastoria?
                   class_name = 'success'
                 else
                   class_name = 'default'
                 end
              %>
              <small>
                <span class="label label-<%= class_name %>">MA</span>
              </small>
          <% end %>
          <% if @listing.export_to_zumper? %>
              <%
                 if @listing.exported_to_zumper?
                   class_name = 'success'
                 else
                   class_name = 'default'
                 end
              %>
              <small>
                <span class="label label-<%= class_name %>">ZU</span>
              </small>
          <% end %>
        </h1>

      </div>

      <div class="col-md-4">
        <h2 class="text-right"><%= number_to_currency(@listing.price) %></h2>
      </div>
    </div>
    <p>
      <% if signed_in? %>
          <% if current_user?(@listing.user) || current_user.admin? %>
              <%= link_to 'Edit listing', edit_listing_path(@listing), class: 'btn btn-default', role: 'button' %>
              <!-- TODO: make post request via form -->
              <%= link_to 'Copy listing', copy_listing_path(@listing), class: 'btn btn-default', role: 'button' %>
              <%= link_to 'Delete listing', @listing, method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-default', role: 'button' %>
              <%= link_to 'History', history_records_path(listing_id: @listing.id), class: 'btn btn-default', role: 'button' %>
          <% end %>
      <% end %>
      <%= link_to 'Download Flyer', listing_path(@listing, :format => 'pdf'), class: 'btn btn-primary', role: 'button' %>
    </p>

    <div class="row">
      <% if @listing.user.present? %>
          <div class="col-md-12">
            <h3><span class="property_type">Agent:</span> <%= @listing.user.try :name %>
              <%= link_to 'View agent', @listing.user, class: 'btn btn-xs btn-primary', role: 'button' %>
              <%= mail_to @listing.user.email, 'Contact agent', class: 'btn btn-xs btn-primary', role: 'button' %>
            </h3>
          </div>
      <% end %>

      <% unless @listing.landlord.nil? %>
          <div class="col-md-12">
            <h3>
              <span class="property_type">Landlord:</span> <%= @listing.landlord %>
            </h3>
          </div>
      <% end %>

      <% if @listing.access.present? %>
          <div class="col-md-12">
            <h3>
              <span class="property_type">Access:</span> <%= @listing.access %>
            </h3>
          </div>
      <% end %>
    </div>


    <div class="row">
      <div class="col-md-7 connected-carousels">
        <% if @listing.property_photos.count > 0 %>
            <% if @listing.property_photos.count == 1 %>
                <% photo = @listing.property_photos.first %>
                <%= image_tag(photo.photo_url_url, :width => '100%') %>
            <% else %>
                <%= render 'jcarousel' %>
            <% end %>
        <% else %>
            <%= image_tag('no_photo.png', :width => '100%') %>
        <% end %>
      </div>

      <div class="col-md-5 property-rooms">
        <p><%= @listing.type_of_space_id %></p>

        <p>
          <%if @listing.dividable? %>
              Dividable
          <% else %>
              Not dividable
          <% end %>
        </p>

        <p>
          <%if @listing.taxes_included? %>
              Taxes: <%= number_to_currency(@listing.taxes_amount) %>
          <% else %>
              Taxes not included
          <% end %>
        </p>

        <p>Days on market: <%= @listing.days_on_market %></p>

        <p>Available at: <%= @listing.available_date %></p>

        <p><%= @listing.status.try :name %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-7 property-description">
        <%= @listing.description %>
      </div>
      <div class="col-md-5 property-size text-right">
        <div id="map-canvas"></div>
      </div>
    </div>

<% end %>

app/views/listings/toggle_favorite.js.erb
var form = $('#star'+ <%= @listing.id %>);
form.replaceWith("<%= j render('star_form', checked: @checked, listing_id: @listing.id) %>");