config/routes.rb
HorowitzRealEstate::Application.routes.draw do
  get "history_record/index"
  get "city/index"
  get "neighborhoods/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :listings do
    member do
      get :copy
      post :toggle_favorite
    end
    collection do
      post :create_email
      post :send_email
    end
  end
  resources :neighborhoods
  resources :history_records, only: [:index]

  resources :reports, only: [] do
    collection do
      get :listings_by_period
      get :rented_listings_by_period
    end
  end

  root  'listings#index'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_many :listings
  has_many :favorites

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates_presence_of :password, :on => :create
  validates :password, length: { minimum: 6 }, :if => :password_present?

  mount_uploader :avatar, ImageUploader

  scope :active_users, -> { where( active: true ) }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end 

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

    def password_present?
      password.present? || password_confirmation.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.active_users.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @favorites_ids = current_user.favorites.pluck :listing_id

    if sort_column.include? '.'
      parts = sort_column.split('.')
      @listingss = @user.listings.includes(parts.first).order("#{parts.first.pluralize}.#{parts.last}" + ' ' + sort_direction)
    else
      @listingss = @user.listings.order(sort_column + ' ' + sort_direction)
    end

    #todo: sorting breaks hidden_listings param
    #todo: code dupl with listings_controller.rb
    if params[:status].present?
      if params[:status] == 'Active'
        @listingss = @listingss.available_listings
      elsif params[:status] == 'Unavailable'
        @listingss = @listingss.hidden_listings
      elsif params[:status] == 'Pending'
        @listingss = @listingss.pending_listings
      end
    else
      @listingss = @listingss.available_listings
    end

    @listingss = @listingss.ids_filter(params[:ids]) if params[:ids].present? && params[:ids] != ['']

    sale_obj = ListingType.find_by_name('Sale')

    @sale_id = ListingType.find_by(name: 'Sale').id
    @rental_id = ListingType.find_by(name: 'Rental').id
    @commercial_id = ListingType.find_by(name: 'Commercial').id

    if params[:display].present?
      @display = params[:display]
    else
      @display = 'thumb_list'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #sign_in @user
      flash[:success] = 'User created.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.active = false
    user.save
    flash[:success] = 'User destroyed.'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :avatar, :phone, :fax, :biography,
                                 :address, :license_type, :license_no, :social_security_no, :commision_split, :naked_apartments_account)
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin?
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_common_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone %>
  <%= f.phone_field :phone, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :fax %>
  <%= f.phone_field :fax, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :biography %>
  <%= f.text_area :biography, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>



app/views/users/_password_form.html.erb
<%= form_for(user, role: 'form', id: "password_from", remote: true ) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
	<div class="form-group">
	  <%= f.label :password %>
	  <%= f.password_field :password, class: "form-control" %>
	</div>
	<div class="form-group">
	  <%= f.label :password_confirmation, "Confirm Password" %>
	  <%= f.password_field :password_confirmation, class: "form-control" %>
	</div>

	<%= f.submit "Save password", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li class="list-group-item">
  <%= link_to user do %>
      <%= user.name %>
      <div class="pull-right">
          <% if current_user.admin? %>
              <%= link_to edit_user_path(user), "aria-label"=> "edit" do %>
                  <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
          <% end %>

          <% if current_user.admin? && !current_user?(user) %>
              <%= link_to user, method: :delete, data: { confirm: "You sure?" } do %>
                  <span class="glyphicon glyphicon-trash"></span>
              <% end %>
          <% end %>
      </div>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit agent info') %>
<h1>Edit agent info</h1>

<%= form_for(@user, role: 'form') do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="row">  

  <aside class="col-sm-4">    
    <section>
      <%= image_tag(@user.avatar_url) %>
    </section>
    <section>
      <%= f.hidden_field(:avatar_cache) %>
      <%= f.file_field(:avatar, class: 'form-control') %>
    </section>    
  </aside>
  <div class="col-sm-8">
    <% if current_user.admin? %>
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#common" role="tab" data-toggle="tab">Common</a></li>
        <li><a href="#spec" role="tab" data-toggle="tab">Special</a></li>        
      </ul>
    <% end %>

    <% if current_user.admin? %>
      <div class="tab-content">
        <div class="tab-pane active" id="common">
    <% end %> 
    <%= render 'common_fields', f: f %>

    <% if current_user.admin? %>
        </div>
        <div class="tab-pane" id="spec">
          <div class="form-group">
            <%= f.label :license_type %>
            <%= f.text_field :license_type, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :license_no %>
            <%= f.text_field :license_no, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :social_security_no %>
            <%= f.text_field :social_security_no, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :commision_split %>
            <%= f.text_field :commision_split, class: 'form-control' %>
          </div>

          <div class="form-group">
            <label>
              <%= f.check_box :naked_apartments_account %> Has Naked Apartments Account
            </label>
          </div>
        </div>
      </div>
    <% end %> 

    <%= f.submit 'Save changes', class: 'btn btn-large btn-primary' %>
  </div>
  
</div>
<% end %>    

app/views/users/edit.js.erb
$('#password_div').html('<%= j render partial: 'password_form', locals: { user: @user } %>');

app/views/users/index.html.erb
<% provide(:title, 'Agents') %>
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">
        <h1>Agents</h1>
    </div>
    <% if current_user.admin? %>
    <%= link_to "Add", new_user_path, class: "btn btn-primary", role: "button" %>
    <p>
    <% end %>

    <%= will_paginate %>

    <ul id="users" class="list-group">
      <%= render @users %>
    </ul>


    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'New user') %>
<h1>New user</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-sm-4">
    <section>
      <%= image_tag(@user.avatar_url, width: 180, height: 220) %>
    </section>
    <section class="name">
      <p><span class="glyphicon glyphicon-user"></span> <%= @user.name %>

      <p><span class="glyphicon glyphicon-earphone"></span> <%= @user.phone %>

      <p><span class="glyphicon glyphicon-envelope"></span> <%= mail_to @user.email %>
    </section>
    <section>

      <% if current_user.admin? %>
          <div class="btn-group">
            <%= link_to 'edit', edit_user_path(@user), method: :get, class: 'btn btn-primary pull-left' %>
          </div>
      <% end %>

      <% if current_user.admin? && !current_user?(@user) %>
          <div class="btn-group">
            <%= link_to 'delete', @user, method: :delete,
                          data: {confirm: "You sure?"}, class: 'btn btn-danger pull-left' %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="col-sm-8">
    <div class="row">
      <div class="col-sm-12">
        <h2>Listings
        <span class="pull-right">
          <%= form_tag({}, :method => :get, role: 'form', class: 'form-inline', id: 'filter_form') do -%>
              <%= hidden_field_tag 'ids[]', params[:ids] %>
            <div class="form-group">
              <%= select_tag 'status',
                             options_for_select(%w(Active Pending Unavailable),
                                                (params['status'] if params['status'].present?)),
                             class: 'form-control', onchange: 'this.form.submit();' %>
            </div>


              <%= link_to "Create rental", new_listing_path(listing_type_id: @rental_id), role: 'button', class: "btn btn-primary" %>
              <%= link_to "Create sale", new_listing_path(listing_type_id: @sale_id), role: 'button', class: "btn btn-primary" %>
              <%= link_to 'Create commercial', new_listing_path(listing_type_id: @commercial_id), role: 'button', class: 'btn btn-primary' %>
          <% end %>
        </span>

        </h2>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <% if @user.listings.any? %>
              <%= form_tag create_email_listings_path, id: 'listings_from' do %>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                      <tr>
                        <th colspan="2"><a href="#" id="narrow_button" class="btn btn-default btn-xs">Narrow</a></th>
                        <th><%= sortable_link 'street_address' %></th>
                        <th><%= sortable_link 'unit_no', 'Unit' %></th>
                        <th><%= sortable_link 'neighborhood.name', 'Neighborhood' %></th>
                        <th><%= sortable_link 'bed.name', 'Beds' %></th>
                        <th><%= sortable_link 'price' %></th>
                        <th><%= sortable_link 'available_date' %></th>
                        <th><%= sortable_link 'status.name', 'Status' %></th>
                        <th><%= sortable_link 'user.name', 'Agent' %></th>
                      </tr>
                      </thead>
                      <tbody>
                      <%= render @listingss %>
                      </tbody>
                    </table>
                  </div>
                  <%= submit_tag 'Email client' %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
$('#error_explanation').remove();
<% if @user.errors.any? %>
	$('#password_from').prepend("<%= j render partial: 'shared/error_messages', locals: {object: @user } %>");
<% else %>	
	$('#password_div').replaceWith('<%= link_to "change_password",  edit_user_path(@user), remote: true %>');	
<% end  %>