config/routes.rb
HorowitzRealEstate::Application.routes.draw do
  get "history_record/index"
  get "city/index"
  get "neighborhoods/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :listings do
    member do
      get :copy
      post :toggle_favorite
    end
    collection do
      post :create_email
      post :send_email
    end
  end
  resources :neighborhoods
  resources :history_records, only: [:index]

  resources :reports, only: [] do
    collection do
      get :listings_by_period
      get :rented_listings_by_period
    end
  end

  root  'listings#index'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user, only: [:create, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html do
        @neighborhood = Neighborhood.new
        @neighborhoods = Neighborhood.all
      end
			format.json do 				
				render :json => Neighborhood.where("lower(name) like lower(?)", "%#{params[:term]}%").map{|neighborhood| {id: neighborhood.id, name: neighborhood.name, value: neighborhood.name}}
			end			
		end
  end

  def create
    @neighborhood = Neighborhood.new(neighborhood_params)
    respond_to do |format|
      if @neighborhood.save
        format.html do
          flash[:success] = "Points was added!"
          redirect_to neighborhoods_path
        end
        format.js
      else
        format.html do
          @neighborhood = Neighborhood.new
          render 'index'
        end
        format.js
      end
    end
  end


  def edit
    @neighborhood = Neighborhood.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @neighborhood = Neighborhood.find(params[:id])
    respond_to do |format|
      if params[:commit] == 'Save'
        if @neighborhood.update_attributes(neighborhood_params)
          format.html do
            flash[:success] = "Data updated"
            redirect_to neighborhoods_path
          end
          format.js
        else
          format.html do
            render 'edit'
          end
          format.js
        end
      else
        format.html { redirect_to neighborhoods_path }
        format.js
      end
    end
  end

  def destroy
    neighborhood = Neighborhood.find(params[:id])
    neighborhood.destroy
    redirect_to :back
  end

  private

  def neighborhood_params
    params.require(:neighborhood).permit(:name)
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_edit.html.erb
<%= form_for(neighborhood, remote: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        <%= f.label :name, class: 'control-label'  %>
        <%= f.text_field :name, class: 'form-control'  %>
    </div>
    <%= f.submit "Save", class: "btn btn-success" %>
    <%= f.submit "Cancel", class: "btn" %>
<% end %>

app/views/neighborhoods/_neighborhood.html.erb
<li id="<%= dom_id neighborhood %>" class ="list-group-item">
  <%= neighborhood.name %>
  <div class="pull-right">
      <%= link_to edit_neighborhood_path(neighborhood), remote: true, "aria-label"=> "edit" do %>
          <span class="glyphicon glyphicon-pencil"></span>
      <% end %>

      <%= link_to neighborhood, method: :delete, data: { confirm: "You sure?" }, title: 'delete this record', "aria-label"=> "delete" do %>
            <span class="glyphicon glyphicon-trash"></span>
      <% end %>
  </div>
</li>

app/views/neighborhoods/create.js.erb
$('#error_explanation').remove();
var new_neighborhood = $('#new_neighborhood');
<% if @neighborhood.errors.any? %>
    new_neighborhood.prepend("<%= j render partial: 'shared/error_messages', locals: {object: @neighborhood } %>");
<% else %>
    new_neighborhood.find('input[type="text"]').val('');
    $('#neighborhoods').prepend("<%= j render partial: 'neighborhood', locals: { neighborhood: @neighborhood } %>");
<% end  %>

app/views/neighborhoods/edit.js.erb
$('#<%= dom_id(@neighborhood) %>').html('<%= j render partial: 'edit', locals: {neighborhood: @neighborhood } %>');

app/views/neighborhoods/index.html.erb
<% provide(:title, 'Neighborhoods') %>
<h1>Neighborhoods</h1>

<%= form_for(@neighborhood, remote: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, 'New record', class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= f.submit "Add neighborhood", class: "btn btn-success" %>
<% end %>
<p>
<ul id="neighborhoods" class="list-group">
  <%= render @neighborhoods %>
</ul>

app/views/neighborhoods/update.js.erb
$('#error_explanation').remove();
<% if @neighborhood.errors.any? %>
    $('#<%= dom_id(@neighborhood, :edit) %>').prepend(
            "<%= j render partial: 'shared/error_messages', locals: {object: @neighborhood } %>"
    );
<% else %>
    $('#<%= dom_id(@neighborhood) %>').replaceWith('<%= j render @neighborhood %>');
<% end  %>