config/routes.rb
HorowitzRealEstate::Application.routes.draw do
  get "history_record/index"
  get "city/index"
  get "neighborhoods/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :listings do
    member do
      get :copy
      post :toggle_favorite
    end
    collection do
      post :create_email
      post :send_email
    end
  end
  resources :neighborhoods
  resources :history_records, only: [:index]

  resources :reports, only: [] do
    collection do
      get :listings_by_period
      get :rented_listings_by_period
    end
  end

  root  'listings#index'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      Horowitz Real Estate    
      <%= link_to 'by elCorsaiR', 'https://www.elance.com/s/elcorsair' %>
    </small> 
     
    <%= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Horowitz Real Estate</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <%
           if signed_in? %>
            <li><%= link_to 'All listings', listings_path %></li>
            <% if current_user.admin? %>
                <li><%= link_to 'Neighborhoods', neighborhoods_path %></li>
            <% end %>
            <li><%= link_to 'Users', users_path %></li>
            <% if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Listing count by period', listings_by_period_reports_path %></li>
                    <li><%= link_to 'Rented listings by period', rented_listings_by_period_reports_path %></li>
                  </ul>
                </li>
            <% end %>
            <li><%= link_to 'Office Forms', 'https://www.dropbox.com/sh/h3jpgfx75rcz1jf/AAD4F-18IEPXOFXEExPxGABqa?dl=0', target: :blank %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Sign out', signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js' %>
    <%= javascript_include_tag '//widget.cloudinary.com/global/all.js' %>

    <% if yield(:java_script) %>
      <%= javascript_include_tag yield(:java_script) %>
    <% end %>
    <%= cloudinary_js_config %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="mainContainer" class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>            
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>